apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: shared-apps
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: {{ .Values.applicationSet.gitRepoUrl }}
          revision: {{ .Values.applicationSet.app.dev.targetRevision }}
          files:
          - path: "helm/apps/**/argocd-config.yaml"
      - list:
          elements:
          - cluster: dev-eks
            name:  dev-eks
            environment: dev
            values:
              project: {{ .Values.applicationSet.project }}
              targetRevision: {{ .Values.applicationSet.app.dev.targetRevision }}
  template:
    metadata:
      name: '{{ template "asKey" "path.basename" }}-{{ template "asKey" "cluster" }}'
      labels:
        environment: '{{template "asKey" "environment"}}'
    spec:
      project: '{{template "asKey" "values.project"}}'
      source:
        repoURL: x
        targetRevision: '{{template "asKey" "values.targetRevision"}}'
        path: '{{ template "asKey" "path" }}'
        helm:
          valueFiles:
            - 'values-{{template "asKey" "environment"}}.yaml'
          values: |
            global:
              environment: {{template "asKey" "environment"}}
              extraSecretReplacement:
                replacement: {{template "asKey" "environment"}}
      destination:
        name: '{{ template "asKey" "name" }}'
        namespace: '{{ template "asKey" "namespace" }}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  syncPolicy:
    preserveResourcesOnDeletion: true # important value, also remember create-only policy for operator
