apiVersion: v2
description: A Helm chart for istio-system
name: istio-system
version: 1.12.0
dependencies:
  - name: base
    version: 1.12.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.12.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    version: 1.12.0
    ## We are using a copy of the chart because it has values.schema.json 
    ## with "additionalProperties": true, that makes the subdepencency fail, when is a dependency
    repository: "file://../../../helm-charts/gateway"
    # repository: https://istio-release.storage.googleapis.com/charts
